export interface Forms{
    formID:number,
    empID:number,
    firstName: string,
    lastName: string,
    email:string,
    type: string,
    eventType: string,
    time: string,
    eventTime:string,
    location: string,
    description: string,
    cost: number,
    rmbrsmntAmt: number,
    empAvailAmt: number,
    gradeFormat: number,
    justification: string,
    directSupervisorApproval: string,
    departmentHeadApproval: string,
    benCoApproval: string,
    rejectionReason: string,
    department: string,
    branch: string
}